name: Java CI

on:
  push:
  workflow_dispatch:  # <-- lets you click “Run workflow” in Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Show files (debug)
      run: ls -la

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # If Main.java and input.json are at repo root. If they’re in a folder, see note below.
    - name: Compile and run
      run: |
        javac Main.java
        java Main < input.json > output.txt

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: assignment-output
        path: output.txt
