name: Run Java Code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Compile and run
      run: |
        javac Main.java
        java Main < input.json > output.txt
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: result
        path: output.txt
